# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: predict.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'predict.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rpredict.proto\"%\n\x11PredictionRequest\x12\x10\n\x08\x66\x65\x61tures\x18\x01 \x03(\x02\")\n\x12PredictionResponse\x12\x13\n\x0bpredictions\x18\x01 \x03(\x02\x32G\n\x11PredictionService\x12\x32\n\x07Predict\x12\x12.PredictionRequest\x1a\x13.PredictionResponseB\x0fZ\rbackend/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'predict_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\rbackend/proto'
  _globals['_PREDICTIONREQUEST']._serialized_start=17
  _globals['_PREDICTIONREQUEST']._serialized_end=54
  _globals['_PREDICTIONRESPONSE']._serialized_start=56
  _globals['_PREDICTIONRESPONSE']._serialized_end=97
  _globals['_PREDICTIONSERVICE']._serialized_start=99
  _globals['_PREDICTIONSERVICE']._serialized_end=170
# @@protoc_insertion_point(module_scope)
